Created tmux session manager

diff --git a/session/session b/session/session
--- a/session/session
+++ b/session/session
@@ -1,8 +1,9 @@
 #!/bin/bash
 
-set -e
+# don't set -e, as we want to be able to check the exit code
+# returned by the fzf-tmux command
 
-SESSION=$(sesh list --icons | fzf-tmux \
+SESSION=$(sesh list --icons --hide-attached | fzf-tmux -p 80%,70% \
 		--no-sort --ansi --border-label ' sesh ' --prompt '⚡  ' \
 		--header '^x tmux kill' \
 		--bind 'tab:down,btab:up' \
@@ -10,9 +11,11 @@ SESSION=$(sesh list --icons | fzf-tmux \
 		--reverse
 )
 
-if [ -n "$SESSION" ]; then
-		sesh connect "$SESSION"
+# if error code is 130, then action was cancelled
+if [ $? -eq 130 ]; then
+	exit
 fi
 
-exit $?
+# otherwise connect to the session
+sesh connect "$SESSION"
 
